version: '3'
services:
  app-role-manager:
    image: app:latest
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    command: node_modules/.bin/next start
    tty: true
