name: Build and test

on: [push]

jobs:
  docker:
    runs-on: self-hosted
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v2

      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Trivy
        run: |
          sudo apt-get -y install curl
          VERSION=$(
              curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | \
              grep '"tag_name":' | \
              sed -E 's/.*"v([^"]+)".*/\1/'
          )

          wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
          tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Build image
        env:
          NPM_REGISTRY: https://npm.pkg.github.com
          NPM_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          export DOCKER_BUILDKIT=1
          [[ -n "${NPM_TOKEN}" ]] && echo "//${NPM_REGISTRY##*://}/:_authToken=${NPM_TOKEN}" > /tmp/.npmrc
          cat /tmp/.npmrc
          docker build -t app:latest --ssh default --secret id=npmrc,src=/tmp/.npmrc .

      - name: Scan image
        run: trivy --exit-code 0 --no-progress app:latest

